//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Projet Chat
//  @ File Name : RFC1664.cpp
//  @ Date : 28/10/2013
//  @ Author : 
//
//

using namespace std;
#include "RFC1664.hpp"
#include "MessagesTypesRFC1664.hpp"

MessagesTypesRFC1664 RFC1664::type() {

}

string RFC1664::createMsgRoomQuit() {

}

string RFC1664::createMsgRoomJoin() {

}

string RFC1664::createMsgBookListRqst() {

}

string RFC1664::createMsgBookListResp() {

}

string RFC1664::createMsgDeco() {

}

string RFC1664::createMsgCon(string clientName) {

}

string RFC1664::createMsgCom() {

}

