//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Projet Chat
//  @ File Name : MessagesTypesRFC1664.h
//  @ Date : 28/10/2013
//  @ Author :
//
//


#if !defined(_MESSAGESTYPESRFC1664_HPP)
#define _MESSAGESTYPESRFC1664_HPP

/**
 * énumeration des types de message possibles
 */
enum MessagesTypesRFC1664 {
    MSG_CON=1,
    MSG_RCON,
    MSG_DECO,
    MSG_COM,
    MSG_ROOM_QUIT,
    MSG_ROOM_JOIN,
    MSG_ROOM_CREATE,
    MSG_BOOK_LIST_RQST,
    MSG_BOOK_LIST_RESP,
    MSG_LIVE,
    ERR_PSEUDO_IN_USE,
    ERR_BAD_MESSAGE,
    MSG_ACK

};

#define MSG_ACK_CONNEXION_FAILED "connecion failed"
#define MSG_ACK_CONNEXION_SUCCESS "connection success"
#define MSG_ACK_REMOVE_CLIENT_FAILED "remove client failed"
#define MSG_ACK_REMOVE_CLIENT_SUCCESS "remove client success"
#define MSG_ACK_ADD_CLIENT_TO_ROOM_FAILED "add client to room failed"
#define MSG_ACK_ADD_CLIENT_TO_ROOM_SUCCESS "add client to room success"
#define MSG_ACK_REMOVE_CLIENT_TO_ROOM_FAILED "remove client from room failed"
#define MSG_ACK_REMOVE_CLIENT_TO_ROOM_SUCCESS "remove client from room success"
#define MSG_ACK_ROOM_CREATE_FAILED "room create failed"
#define MSG_ACK_ROOM_CREATE_SUCCESS "room create success"
#define MSG_ACK_UNKNOWN_CLIENT "unknown client"

#endif  //_MESSAGESTYPESRFC1664_HPP
