//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Projet Chat
//  @ File Name : RFC1664.cpp
//  @ Date : 28/10/2013
//  @ Author :
//
//


#include "RFC1664.hpp"
#include "MessagesTypesRFC1664.hpp"
#include "ErrorCodes.hpp"
#include <cstring>
#include <stdio.h>
#include <string>
#include <sstream>
#include <iostream>

MessagesTypesRFC1664 RFC1664::type(string msg) {
    std::size_t found = msg.find("CON§", 0);
    if (found != string::npos)
        return MSG_CON;

    found = msg.find("DECO§", 0);
    if (found != string::npos)
        return MSG_DECO;

    found = msg.find("ROOM_QUIT§", 0);
    if (found != string::npos)
        return MSG_ROOM_QUIT;

    found = msg.find("ROOM_CREATE§", 0);
    if (found != string::npos)
        return MSG_ROOM_CREATE;

    found = msg.find("ROOM_JOIN§", 0);
    if (found != string::npos)
        return MSG_ROOM_JOIN;

    found = msg.find("BOOK_LIST_RQST§", 0);
    if (found != string::npos)
        return MSG_BOOK_LIST_RQST;

    found = msg.find("COM§", 0);
    if (found != string::npos)
        return MSG_COM;

    found = msg.find("KEEP_ALIVE§", 0);
    if (found != string::npos)
        return MSG_LIVE;

    return ERR_BAD_MESSAGE;

}

string RFC1664::createMsgRoomQuit(string clientName, string roomName) {
    string retour = "ROOM_QUIT§" + clientName + "§" + roomName+"§";
    return retour;
}

string RFC1664::createMsgRoomJoin(string clientName, string roomName) {
    string retour = "ROOM_JOIN§" + clientName + "§" + roomName+"§";
    return retour;
}

string RFC1664::createMsgRoomCreate(string clientName, string roomName) {
    string retour = "ROOM_CREATE§" + clientName + "§" + roomName + "§";
    return retour;
}

string RFC1664::createMsgBookListRqst(string clientName) {
    string retour = "BOOK_LIST_RQST§" + clientName+"§";
    return retour;
}

string RFC1664::createMsgBookListResp(string clientName, string ip, string port, int roomNb, vector<Room*> rooms) {
    string sRoomNb = to_string(roomNb);
    string retour = "BOOK_LIST_RESP§" + clientName + "§" + ip + "§" + port + "§" + sRoomNb+"§";

    vector<Room*>::iterator it;
    for (it = rooms.begin(); it != rooms.end(); ++it) {

        retour += (*it)->getName();
        retour += "§";
    }

    return retour;
}

string RFC1664::createMsgDeco(string clientName) {

    string retour = "DECO§" + clientName+"§";
    return retour;
}

string RFC1664::createMsgCon(string clientName, string addressIp) {
    string retour = "CON§" + clientName + "§" + addressIp +"§";
    return retour;
}

string RFC1664::createMsgCom(string senderName, string receiverName, string message, string roomName) {
    string retour = "COM§" + senderName + "§" + receiverName + "§" + message + "§" + roomName+"§";
    return retour;
}

string RFC1664::createMsgKeepAlive(string clientName) {
    string retour = "KEEP_ALIVE§" + clientName+"§";
    return retour;
}

/*
string RFC1664::fieldFromMesg(string msg, int fieldNb, char delim) {
    string retour;
    istringstream iss(msg);
    string mot;
    //char delim = '§';
    int i = 1;
    while (std::getline(iss, mot, delim) && (i < fieldNb)) {
        //cout << i << endl;
        i++;
        //cout << i << endl;
        //cout << mot << endl;
    }
    //cout << mot<<endl;
    mot.erase(mot.size() - 1, 1);
    retour = mot;

    return retour;
}*/

string RFC1664::fieldFromMesg(string msg, int fieldNb, char delim) {

    string delimiter = "§";
    string retour;
    size_t pos = 0;
    std::string token;
    int i = 0;
    while ((pos = msg.find(delimiter)) != std::string::npos && (i < fieldNb)) {
        i++;
        token = msg.substr(0, pos);
        //retour=token;
        msg.erase(0, pos + delimiter.length());
    }
    retour=token;
    //cout<<retour;

    return retour;
}

