//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Projet Chat
//  @ File Name : RFC1664.h
//  @ Date : 28/10/2013
//  @ Author : 
//
//


#if !defined(_RFC1664_HPP)
#define _RFC1664_HPP

#include "MessagesTypesRFC1664.hpp"

class RFC1664 {
public:
	MessagesTypesRFC1664 type();
	string createMsgRoomQuit();
	string createMsgRoomJoin();
	string createMsgBookListRqst();
	string createMsgBookListResp();
	string createMsgDeco();
	string createMsgCon(string clientName);
	string createMsgCom();
};

#endif  //_RFC1664_HPP
